# Generated by Django 5.1.1 on 2024-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contend', models.TextField()),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
